//
// Created by feyzi on 12.04.2022.
//

#ifndef SIMULATION_DATA_GENERATOR_SPEED_ACCELERATION_DATA_GENERATOR_H
#define SIMULATION_DATA_GENERATOR_SPEED_ACCELERATION_DATA_GENERATOR_H


class Speed_Acceleration_Data_Generator {

};


#endif //SIMULATION_DATA_GENERATOR_SPEED_ACCELERATION_DATA_GENERATOR_H
